# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "atm-insights"
    environment: "production"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # ATM Insights Backend API
  - job_name: "atm-insights-backend"
    static_configs:
      - targets: ["backend:8000"]
    scrape_interval: 15s
    metrics_path: "/api/v1/metrics"
    scrape_timeout: 10s
    params:
      format: ["prometheus"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:8000

  # System Metrics (Node Exporter)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "atm-insights-host"

  # Redis Metrics
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "atm-redis"

  # PostgreSQL Metrics
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "atm-postgres"

  # TimescaleDB specific metrics (if available)
  - job_name: "timescaledb"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 60s
    metrics_path: "/metrics"

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
